---
- name: Publish the persist changes
  ansible.scm.git_publish:
    path: "{{ network_brm_backup_path }}"
    timeout: 120
  when: data_store['scm']['origin']['token'] is undefined

# - name: Publish the changes
#   ansible.scm.git_publish:
#     path: "{{ network_brm_backup_path }}"
#     token: "{{ data_store['scm']['origin']['token'] }}"
#     user: "{{ data_store['scm']['origin']['user'] }}"
#     timeout: 120
#   when: data_store['scm']['origin']['tag'] is not defined

- name: Set Timestamp
  set_fact: time="{{lookup('pipe','date \"+%Y-%m-%d-%H-%M\"')}}"
  run_once: true

- name: Publish the changes
  ansible.scm.git_publish:
    path: "{{ network_brm_backup_path }}"
    token: "{{ data_store['scm']['origin']['token'] }}"
    user: "{{ data_store['scm']['origin']['user'] }}"
    tag:
      annotation: "{{ time }}"
      message: "config_backup"
    timeout: 120
