---
- name: Backup ios Configuration
  cisco.ios.ios_config:
    backup: true
    backup_options:
      dir_path: "{{  network_brm_backup_path }}"
      filename: "{{ inventory_hostname }}.txt"
  register: network_brm_backup

- name: Show Config 
  ansible.builtin.debug:
    msg: "{{ network_brm_backup }}"
